version: '3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./data.json:/app/data.json
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    entrypoint: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]

volumes:
  db_data: